module.exports = {
	parserPreset: "conventional-changelog-evelyn",
	rules: {
		"subject-empty": [2, "never"],
		"subject-case": [1, "always", "start-case"],
		"scope-case": [1, "always", "kebab-case"],
		"type-empty": [2, "never"],
		"type-enum": [2, "always", [
			"Breaking",
			"Major",
			"Feature",
			"Feat",
			"New",
			"Improvement",
			"Improve",
			"Update",
			"Documentation",
			"Docs",
			"Readme",
			"Fix",
			"Accessibility",
			"Access",
			"A11y",
			"Performance",
			"Perf",
			"Package",
			"Upgrade",
			"Config",
			"CI",
			"Build",
			"Lint",
			"Test",
			"Tests",
			"Internal",
			"Refactor",
			"Cleanup",
			"Chore",
			"WIP",
			"Release",
			"Other",
		]],
	},
};
